name: Secret Suite Orchestration (Local)

on:
  workflow_dispatch:
    inputs:
      env_path:
        description: "Path to deploy-all-secret-suite.env"
        required: true
        default: bash/GitDevSecDataAIOps/proxmox/deploy-all-secret-suite.env

jobs:
  deploy:
    runs-on: [local]
    steps:
      - uses: https://github.com/actions/checkout@v4

      - name: Run orchestrator
        env:
          ENV_PATH: ${{ github.event.inputs.env_path }}
        run: |
          set -euo pipefail
          if [[ ! -f "${ENV_PATH}" ]]; then
            echo "Env not found: ${ENV_PATH}" >&2
            exit 1
          fi
          bash bash/GitDevSecDataAIOps/proxmox/deploy-all-secret-suite.sh "${ENV_PATH}"
