#!/usr/bin/env bash
set -euo pipefail
umask 077

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
CS_ROOT="${SCRIPT_DIR}"
while [[ ! -f "${CS_ROOT}/lib/cs-common.sh" ]]; do
  if [[ "${CS_ROOT}" == "/" ]]; then
    echo "cs-common.sh not found" >&2
    exit 1
  fi
  CS_ROOT=$(dirname "${CS_ROOT}")
done
# shellcheck disable=SC1090,SC1091
source "${CS_ROOT}/lib/cs-common.sh"

# shellcheck disable=SC2034
CS_LOG_PREFIX="github-apps-wizard"

if [[ ! -t 0 ]]; then
  cs_die "Interactive wizard requires a TTY"
fi

cs_ui_header "GitHub Apps UI Wizard (Bots)"
cs_ui_note "Este wizard crea un checklist ClickOps y genera JSONL semantico."

ORG_NAME=$(cs_ui_prompt "Owner/Org" "owner")
TARGET_REPO=$(cs_ui_prompt "Repo objetivo (nombre)" "repo")
BOT_COMPLIANCE=$(cs_ui_prompt "Nombre App (compliance)" "ops-compliance-app")
BOT_SECURITY=$(cs_ui_prompt "Nombre App (security)" "ops-security-app")
BOT_PRIVACY=$(cs_ui_prompt "Nombre App (privacy)" "ops-privacy-app")
BOT_SUPPLY=$(cs_ui_prompt "Nombre App (supplychain)" "ops-supplychain-app")
WEBHOOK_URL=$(cs_ui_prompt "Webhook URL (placeholder)" "https://example.local/webhook")
OUTPUT_PATH=$(cs_ui_prompt "Ruta del checklist .md" "${SCRIPT_DIR}/github-apps-bot-clickops.md")
JSONL_PATH=$(cs_ui_prompt "Ruta del JSONL semantico" "${SCRIPT_DIR}/github-apps-bot-clickops.jsonl")

cs_ui_step "Generando checklist en ${OUTPUT_PATH}"

cat <<EOF > "${OUTPUT_PATH}"
# GitHub Apps UI ClickOps - Bot Setup

> Owner/Org: ${ORG_NAME}
> Repo objetivo: ${TARGET_REPO}

## 1) Crear GitHub Apps
- UI: **Settings** → **Developer settings** → **GitHub Apps** → **New GitHub App**
- Apps sugeridas:
  - ${BOT_COMPLIANCE}
  - ${BOT_SECURITY}
  - ${BOT_PRIVACY}
  - ${BOT_SUPPLY}

## 2) Permisos minimos
- Pull requests: **Read/Write**
- Contents: **Read**
- Metadata: **Read**

## 3) Webhooks
- Webhook URL: ${WEBHOOK_URL}
- Secret: definir y guardar en lugar seguro

## 4) Instalar Apps
- UI: GitHub App → **Install App**
- Instalar en org/repo objetivo

## 5) Tokens
- Generar y almacenar tokens fuera de git

---
Generado por wizard: $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

chmod 600 "${OUTPUT_PATH}"
cs_ui_ok "Checklist creado: ${OUTPUT_PATH}"

cs_ui_step "Generando JSONL semantico en ${JSONL_PATH}"
ORG_NAME="${ORG_NAME}" TARGET_REPO="${TARGET_REPO}" WEBHOOK_URL="${WEBHOOK_URL}" \
BOT_COMPLIANCE="${BOT_COMPLIANCE}" BOT_SECURITY="${BOT_SECURITY}" BOT_PRIVACY="${BOT_PRIVACY}" \
BOT_SUPPLY="${BOT_SUPPLY}" JSONL_PATH="${JSONL_PATH}" \
python3 - <<'PY'
import json
import os
from datetime import datetime, timezone

org = os.environ["ORG_NAME"]
repo = os.environ["TARGET_REPO"]
webhook = os.environ["WEBHOOK_URL"]
apps = [
    os.environ["BOT_COMPLIANCE"],
    os.environ["BOT_SECURITY"],
    os.environ["BOT_PRIVACY"],
    os.environ["BOT_SUPPLY"],
]
jsonl_path = os.environ["JSONL_PATH"]

record = {
    "record_id": f"bot-github-apps-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
    "platform": "github",
    "category": "github-apps",
    "title": "GitHub Apps Bot Setup",
    "status": "info",
    "repo": {
        "owner": org,
        "name": repo,
        "url": f"https://github.com/{org}/{repo}",
    },
    "actors": apps,
    "steps": [
        {"step_id": "apps-create", "title": "Create GitHub App", "ui_path": "Settings > Developer settings > GitHub Apps > New GitHub App", "required": True},
        {"step_id": "perms-config", "title": "Set permissions", "ui_path": "GitHub App settings > Permissions", "required": True},
        {"step_id": "webhook-secret", "title": "Configure webhook secret", "ui_path": "GitHub App settings > Webhooks", "required": False},
        {"step_id": "install-app", "title": "Install app", "ui_path": "GitHub App settings > Install App", "required": True},
    ],
    "expected": ["GitHub App created", "App installed", "Webhook configured"],
    "checks": [{"check_id": "ui.checklist", "status": "info", "detail": "Generated by wizard"}],
    "evidence": [{"type": "note", "ref": "wizard-output", "notes": "Generated by github-apps wizard"}],
    "created_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
    "notes": "Placeholders only.",
    "placeholders": {"webhook_url": webhook},
}

with open(jsonl_path, "w", encoding="utf-8") as fh:
    fh.write(json.dumps(record, ensure_ascii=True) + "\n")
PY

chmod 600 "${JSONL_PATH}"
cs_ui_ok "JSONL creado: ${JSONL_PATH}"
